# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - hhvm
  - nightly

notifications:
  email:
    recipients:
      - fulviocanducci@hotmail.com
    on_success: always

before_script:
  - composer install

script:
  - vendor/bin/phpspec run
